build:
  image: nbo/ghcjs-gui:20160201
  environment:
    - AWS_ACCESS_KEY_ID=$$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$$AWS_SECRET_ACCESS_KEY
  commands:
    - date
    - mkdir -p dist/proto
    - scripts/genproto > /dev/null
    - scripts/gencabal
    - cd $DRONE_DIR/build_7.10/backend
    - stack build --copy-bins --fast
    - cd $DRONE_DIR
    - 'if [ "$DRONE_BRANCH" = production -o "$DRONE_BRANCH" = fogger ]; then ./upload_backend.sh; fi'
    - cd $DRONE_DIR/nodelab
    - npm install
    - bower install --allow-root
    - mkdir -p .stack-work/install/x86_64-osx/custom-nbo-gui-20160201/ghcjs-0.2.0.20160201_ghc-7.10.3/bin/nodelab.jsexe/
    - touch .stack-work/install/x86_64-osx/custom-nbo-gui-20160201/ghcjs-0.2.0.20160201_ghc-7.10.3/bin/nodelab.jsexe/all.js
    - brunch build # --env production
    - 'if [ "$DRONE_BRANCH" = production -o "$DRONE_BRANCH" = fogger ]; then ./upload_dist.sh; fi'
    - date

notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    username: 'typechecker'
    channel: '#cd'
    on_started: false
    on_success: true
    on_failure: true
  webhook:
    urls:
      - http://yc.nodelab.io/builds/L3EmGzBpajHukZ7cjnZzvk7aqIKJI30bzp0vgOLY4NShPTSojgvPs88APCG3mPa3

publish:
  docker:
    username:  $$DOCKERHUB_USER
    password:  $$DOCKERHUB_PASS
    email: $$DOCKERHUB_EMAIL
    repo: kfigiela/nodelab
    tag: $$BRANCH
    file: Dockerfile
    insecure: false
    storage_driver: aufs
    when:
      branch: [production, fogger]
