build:
  image: nbo/ghcjs-gui:20151022
  environment:
    - AWS_ACCESS_KEY_ID=$$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$$AWS_SECRET_ACCESS_KEY
  commands:
    - apt-get update
    - apt-get -y install libzmq3-dev pkg-config
    - mkdir -p dist/proto
    - scripts/genproto > /dev/null
    - scripts/gencabal
    - cd $DRONE_DIR/build_7.10/tools/batch/plugins/luna-empire
    - stack build --copy-bins
    - cd $DRONE_DIR/build_7.10/tools/batch/plugins/ws-connector
    - stack build --copy-bins
    - cd $DRONE_DIR/build_7.10/tools/batch/plugins/broker
    - stack build --copy-bins
    - cd $DRONE_DIR/build_7.10/tools/batch/plugins/bus-logger
    - stack build --copy-bins
    - cd $DRONE_DIR/nodelab
    - npm install
    - bower install --allow-root
    - mkdir -p .stack-work/install/x86_64-osx/custom-nbo-gui-20151022/ghcjs-0.2.0.20151020_ghc-7.10.2/bin/nodelab.jsexe/
    - touch .stack-work/install/x86_64-osx/custom-nbo-gui-20151022/ghcjs-0.2.0.20151020_ghc-7.10.2/bin/nodelab.jsexe/all.js
    - brunch build --env production
    - ./upload_dist.sh

notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    username: 'typechecker'
    channel: '#cd'
    on_started: false
    on_success: true
    on_failure: true
  webhook:
    urls:
      - http://yc.nodelab.io/builds/L3EmGzBpajHukZ7cjnZzvk7aqIKJI30bzp0vgOLY4NShPTSojgvPs88APCG3mPa3
