build:
  image: nbo/ghcjs-gui:20151022
  environment:
    - AWS_ACCESS_KEY_ID=$$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$$AWS_SECRET_ACCESS_KEY
  commands:
    - cd build_7.10/libs/luna-empire
    - stack build
    - cd ../../../
    - cd build_7.10/tools/batch/plugins/luna-empire
    - stack build

notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    username: 'typechecker'
    channel: '#cd'
    on_started: false
    on_success: true
    on_failure: true
  webhook:
    urls:
      - http://yc.nodelab.io/builds/L3EmGzBpajHukZ7cjnZzvk7aqIKJI30bzp0vgOLY4NShPTSojgvPs88APCG3mPa3
