clone:
  recursive: true
build:
  backend:
    image: lunalang/buildenv:alpine-7.10
    auth_config:
      username:  $$DOCKERHUB_USER
      password:  $$DOCKERHUB_PASS
      email: $$DOCKERHUB_EMAIL
    commands:
      - date
      - mkdir -p .stack
      - export STACK_ROOT=$DRONE_DIR/.stack
      - mkdir -p dist/proto
      - scripts/genproto
      - scripts/gencabal
      - cd $DRONE_DIR/build/backend
      - stack build --only-snapshot
      - stack build --copy-bins --fast
      - cd $DRONE_DIR
      - ./run_tests.sh
  frontend:
    image: lunalang/buildenv:alpine-7.10-ghcjs
    auth_config:
      username:  $$DOCKERHUB_USER
      password:  $$DOCKERHUB_PASS
      email: $$DOCKERHUB_EMAIL
    commands:
      - date
      - mkdir -p .stack-ghcjs
      - export STACK_ROOT=$DRONE_DIR/.stack-ghcjs
      - cd $DRONE_DIR/nodelab
      - npm install
      - bower install --allow-root
      - brunch build --env production
      - date
cache:
  mount:
    - .stack
    - .stack-ghcjs

notify:
  slack:
    webhook_url: $$SLACK_URL
    username: "new_byte_order: $$BRANCH"
    channel: "#cd"
    on_started: false
    on_success: true
    on_failure: true
    template: "<{{ system.link_url }}/{{ repo.full_name }}/{{ build.number }}|build #{{ build.number}}>: *{{ build.status }}* by {{ build.author }}: <https://bitbucket.org/{{ repo.full_name }}/commits/$$COMMIT|$${COMMIT:0:7}>\n\n{{ build.message }}"

publish:
  docker:
    username:  $$DOCKERHUB_USER
    password:  $$DOCKERHUB_PASS
    email: $$DOCKERHUB_EMAIL
    repo: lunalang/luna-testing
    tag:
      - $${BRANCH##docker/}-latest
      - $${BRANCH##docker/}-b$$BUILD_NUMBER
    file: Dockerfile
    insecure: false
    storage_driver: aufs
    when:
      branch: docker/*
