resolver: ghc-7.10
use-ghcjs: true
packages:
  - .
  - ../libs/utils
  - ../libs/convert
  - ../libs/luna/typechecker
  - ../third-party/fgl
  - ../third-party/graphviz-2999.17.0.2.2
extra-deps:
  - HUnit-1.2.5.2
  - MissingH-1.3.0.1
  - MonadRandom-0.4
  - QuickCheck-2.8.1
  - StateVar-1.1.0.1
  - adjunctions-4.2.1
  - ansi-terminal-0.6.2.1
  - ansi-wl-pprint-0.6.7.2
  - base-4.8.0.0
  - base-orphans-0.4.3
  - bifunctors-5
  - colour-2.3.3
  - comonad-4.2.7.2
  - cond-0.4.1.1
  - constraints-0.4.1.3
  - contravariant-1.3.2
  - convertible-1.1.1.0
  - data-default-0.5.3
  - data-default-class-0.0.1
  - data-default-instances-base-0.0.1
  - data-default-instances-containers-0.0.1
  - data-default-instances-dlist-0.0.1
  - data-default-instances-old-locale-0.0.1
  - distributive-0.4.4
  - either-4.4.1
  - errors-1.4.7
  - exceptions-0.8.0.2
  - free-4.12.1
  - generic-deriving-1.8.0
  - ghcjs-dom-0.2.1.0
  - haskell-lexer-1.0
  - hslogger-1.2.9
  - hspec-2.1.10
  - hspec-core-2.1.10
  - hspec-discover-2.1.10
  - hspec-expectations-0.7.1
  - kan-extensions-4.2.2
  - lens-4.12.3
  - mmorph-1.0.4
  - monad-control-1.0.0.4
  - monad-loops-0.4.3
  - nats-1
  - network-2.6.2.1
  - newtype-0.2
  - optparse-applicative-0.11.0.2
  - parsec-3.1.9
  - polyparse-1.11
  - prelude-extras-0.4
  - pretty-show-1.6.8.2
  - profunctors-5.1.1
  - protocol-buffers-2.1.4
  - psqueues-0.2.0.2
  - quickcheck-io-0.1.1
  - random-1.1
  - reactive-banana-0.8.1.2
  - reflection-2
  - regex-base-0.93.2
  - regex-compat-0.95.1
  - regex-posix-0.95.2
  - safe-0.3.9
  - semigroupoids-5.0.0.3
  - semigroups-0.16.2.2
  - setenv-0.1.1.3
  - split-0.2.2
  - tagged-0.8.1
  - temporary-1.2.0.3
  - tf-random-0.5
  - transformers-base-0.4.4
  - transformers-compat-0.4.0.4
  - utf8-string-1
  - vault-0.3.0.4
  - void-0.7
  - wl-pprint-text-1.1.0.4