flags: {}
packages:
- '.'
- /Users/kamilfigiela/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/ghcjs-boot/ghcjs/ghcjs-base/
- /Users/kamilfigiela/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/ghcjs-prim
- /Users/kamilfigiela/Flowbox/toolchain/ghcjsi/ghcjs-dom
extra-deps:
- reactive-banana-0.8.1.2
resolver: nightly-2015-07-24
