packages:
- ../../../libs/config
- ../../../libs/luna/build
- ../../../libs/luna/core
- ../../../libs/luna/distribution
- ../../../libs/luna/initializer
- ../../../libs/luna/pass
- ../../../libs/luna/target/ghchs
- ../../../libs/utils
- ../../../third-party/fgl
- ../../../tools/lunac
extra-deps:
- HMap-1.2.4
- OneTuple-0.2.1
- assert-0.0.1.2
- phonetic-code-0.1.1.1
- tuple-0.3.0.2
- zippers-0.2
resolver: nightly-2015-07-24

