packages:
- ../third-party/binary
- ../third-party/accelerate-cuda
- ../third-party/HMap
- ../libs/task-queue
- ../libs/config
- ../libs/luna/interpreter
- ../libs/data/codec/exr
- ../libs/data/serialization
- ../libs/repo-manager
- ../libs/luna/core
- ../tools/aws/instance-manager
- ../libs/luna/build
- ../libs/luna/distribution-old
- ../libs/batch/batch
- ../tools/aws/account-manager-mock
- ../libs/batch/plugins/project-manager-api
- ../tools/wrappers
- ../tools/initializer
- ../libs/data/dynamics/particles
- ../libs/luna/protobuf
- ../libs/aws
- ../libs/data/graphics
- ../libs/ws-connector
- ../libs/bus
- ../libs/utils
- ../third-party/linear-accelerate
- ../tools/batch/plugins/bus-logger
- ../third-party/algebraic
- ../third-party/accelerate
- ../third-party/accelerate-fft
- ../tools/batch/plugins/interpreter
- ../tools/batch/plugins/ur-manager
- ../tools/aws/account-manager
- ../tools/lunac
- ../libs/luna/typechecker
- ../libs/luna/initializer
- ../libs/batch/plugins/ur-manager
- ../libs/luna/target/ghchs
- ../libs/batch/plugins/project-manager
- ../libs/luna/interpreter-runtime
- ../tools/batch/plugins/s3-file-manager
- ../libs/num-conversion
- ../third-party/fgl
- ../libs/luna/protobuf-old
- ../tools/batch/plugins/project-manager
- ../libs/luna/pass
- ../libs/luna/parser2-old
- ../libs/rpc
- ../tools/batch/plugins/broker
- ../tools/batch/plugins/file-manager
- ../libs/luna/pass-old
- ../tools/batch/plugins/parser
- ../third-party/imagemagick
- ../libs/luna/distribution
- ../tools/batch/plugins/plugin-manager
- ../third-party/accelerate-io
- ../libs/batch/plugins/file-manager
- ../libs/gui-mockup
- ../third-party/mainland-pretty
- ../libs/data/accelerate/thrust
- ../libs/luna/interpreter-old
- ../libs/doc/markup
resolver: '7.10'

