version: 2
jobs:
  backend:
    docker:
      - image: fpco/stack-build:lts-9
    steps:
      - checkout
      - run: stack setup --stack-yaml=build-config/backend/stack.yaml
      - run: stack build --stack-yaml=build-config/backend/stack.yaml --fast
  frontend:
    docker:
      - image: fpco/stack-build:lts-9
    steps:
      - checkout
      - run: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
      - run:
          command: |
            source ~/.bashrc
            nvm use lts/*
            stack setup --stack-yaml=luna-studio/stack.yaml --ghcjs-boot-options --no-prof
            stack build --stack-yaml=luna-studio/stack.yaml --fast
workflows:
  version: 2
  percommit:
    jobs:
      - backend
      - frontend
