version: 2
jobs:
  backend:
    docker:
      - image: fpco/stack-build:lts-9
    steps:
      - checkout
      - run: stack setup --stack-yaml=build-config/backend/stack.yaml
      - run: stack build --stack-yaml=build-config/backend/stack.yaml --fast
  frontend:
    docker:
      - image: fpco/stack-build:lts-9
    steps:
      - checkout
      - run: stack setup --stack-yaml=luna-studio/stack.yaml --ghcjs-boot-options --no-prof
      - run: stack build --stack-yaml=luna-studio/stack.yaml --fast
workflows:
  version: 2
  percommit:
    jobs:
      - backend
      - frontend
