packages:
- ../../../../libs/aws
- ../../../../libs/rpc
- ../../../../libs/utils
- ../../../../third-party/fgl
- ../../../../tools/aws/instance-manager
extra-deps:
- aws-0.11.1
- aws-sdk-0.12.4
- blaze-builder-0.3.3.4
- blaze-builder-enumerator-0.2.0.7
- monad-control-0.3.3.1
- protocol-buffers-2.1.3
- protocol-buffers-descriptor-2.1.3
- simple-config-1.2.2.1
- strptime-1.0.10
- utf8-string-0.3.8
resolver: lts-2.18

