resolver: lts-8.11
compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b

ghc-options:
  node-editor: -DGHCJS_BROWSER
  text-editor: -DGHCJS_BROWSER
extra-deps:
  - cond-0.4.1.1
  - datetime-0.3.1
  - ghcjs-dom-0.7.0.4
  - ghcjs-dom-jsffi-0.7.0.4

packages:
- {location: ./node-editor}
- {location: ./text-editor}
- {extra-dep: true, location: ./lib}
- {extra-dep: true, location: ../libs/luna-studio-common}
- {extra-dep: true, location: ../libs/scope-searcher}
- extra-dep: true
  location: {commit: 07eaf49447cc02fb94a7dfcd0cbbb52727e0af97, git: 'https://github.com/luna/container.git'}
- extra-dep: true
  location: {commit: d2e5ee90d59e2492c14aa825bcd9deef0af2f179, git: 'https://github.com/luna/convert.git'}
- extra-dep: true
  location: {commit: a6afda3b96efe00938aba61ac12a2f5f2134ff3d, git: 'https://github.com/luna/data-construction.git'}
- extra-dep: true
  location: {commit: 8a5773adba33d71a311ba0b4123b744213b0be91, git: 'https://github.com/luna/data-layer.git'}
- extra-dep: true
  location: {commit: b5f02ced2912501d923c07950789fbcf44a6a9ce, git: 'https://github.com/luna/data-prop.git'}
- extra-dep: true
  location: {commit: 9da4c9b2534693cfe82adeb37f12eaadacb41e62, git: 'https://github.com/luna/data-repr.git'}
- extra-dep: true
  location: {commit: 5307f2e636fa9b80d991df183f7a594948ad2ad1, git: 'https://github.com/luna/data-rtuple.git'}
- extra-dep: true
  location: {commit: 71a26613c43f76c3f5b61dc99046262065b91694, git: 'https://github.com/luna/dependent-state.git'}
- extra-dep: true
  location: {commit: ae5c538fd1d1d85b47c608c72a84330deb6850d0, git: 'https://github.com/luna/functor-utils.git'}
- extra-dep: true
  location: {commit: 7917cc1d84e421823b6291bb4c5ec065a29e9c42, git: 'https://github.com/luna/hsprocessing.git'}
- extra-dep: true
  location: {commit: 9f64b89d26d6064580669538e51c24c50320c2fd, git: 'https://github.com/luna/impossible.git'}
- extra-dep: true
  location: {commit: b45aacbf536194bee5a3c6041231fde1dabdc8fe, git: 'https://github.com/luna/lens-utils.git'}
- extra-dep: true
  location: {commit: c6fedf292f4c049e9f450c8d0622102afab786f8, git: 'https://github.com/luna/luna.git'}
  subdirs: [syntax/text/lexer]
- extra-dep: true
  location: {commit: b00b9a7d91c2d4909574ff679b88b49df7282e64, git: 'https://github.com/luna/monoid'}
- extra-dep: true
  location: {commit: 7c7a6d657e7db8c3dcd80fbed0a7e02e02f43ae3, git: 'https://github.com/luna/monad-branch'}
- extra-dep: true
  location: {commit: a00f3614c6af85d6ee87087f5fd6e886677327c1, git: 'https://github.com/luna/parsert'}
- extra-dep: true
  location: {commit: 06e78228e9217568db204f86c66b4f0509e3d753, git: 'https://github.com/luna/prologue.git'}
- extra-dep: true
  location: {commit: ad94b1f2e4bc87b81853ff746b64c59b3eae7f09, git: 'https://github.com/luna/react-flux'}
- extra-dep: true
  location: {commit: 19cd9bd99caf29424def070783526335ee5bff8a, git: 'https://github.com/luna/text-processing.git'}
- extra-dep: true
  location: {commit: c234d2d5285a770eea81af26c465193e88d44a24, git: 'https://github.com/luna/typelevel.git'}
- extra-dep: true
  location: {commit: 845acded84033cdcdac3d754c5c0b1fccfa4f299, git: 'https://github.com/luna/vector-text.git'}
- extra-dep: true
  location: {commit: ddfcd1e0372b93e947b380b911c123fe67227b21, git: 'https://github.com/luna/visualization-api.git'}
