resolver:
  name: nbo-gui-20151022
  location: https://bitbucket.org/NewByteOrder/stack-snapshots/raw/master/nbo-gui-20151022.yaml
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151020_ghc-7.10.2:
        url: "https://s3-eu-west-1.amazonaws.com/nbo-toolchain/ghcjs/ghcjs-0.2.0.20151020-dupa.tar.gz"
ghc-options:
  nodelab: -DGHCJS_BROWSER
packages:
  - .
  - ../libs/utils
  - ../libs/luna/protobuf-old-gen
  - ../libs/batch/batch-protobuf
  - ../libs/data/serialization
  - ../libs/batch/plugins/project-manager-api
  - ../tools/batch/plugins/interpreter-api
extra-deps:
  - ghcjs-dom-0.2.3.0
