resolver: 
  name: nbo
  location: nbo-snapshot.yaml
#resolver: lts-3.10
compiler: ghcjs-0.2.0.20151020_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151020_ghc-7.10.2:
        url: "https://s3-eu-west-1.amazonaws.com/nbo-toolchain/ghcjs/ghcjs-0.2.0.20151020.tar.gz"
ghc-options:
  nodelab: -DGHCJS_BROWSER
packages:
  - .
  - ../libs/utils
  - ../libs/convert
  - ../libs/luna/typechecker
  - ../libs/luna/protobuf-old-gen
  - ../libs/batch/batch-protobuf
  - ../libs/data/serialization
  - ../libs/batch/plugins/project-manager-api
  - ../tools/batch/plugins/interpreter-api
  - ../third-party/graphviz-2999.17.0.2.2
  - ../third-party/ghcjs-dom

#extra-deps:
# - reactive-banana-0.9.0.0
# - errors-1.4.7
