resolver:
  name: nbo-gui-20151022
  location: https://bitbucket.org/NewByteOrder/stack-snapshots/raw/master/nbo-gui-20151022.yaml
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151020_ghc-7.10.2:
        url: "https://s3-eu-west-1.amazonaws.com/nbo-toolchain/ghcjs/ghcjs-0.2.0.20151020-dupa.tar.gz"
ghc-options:
  nodelab: -DGHCJS_BROWSER
packages:
  - .
  - ../libs/luna-empire-api
  - ../libs/luna-empire-api-json
  - ../libs/utils
  - location:
      git: git@github.com:wdanilo/prologue.git
      commit: 9ba882921b6e2527923bbb0f9ba54c41b43a8135
  - location:
      git: git@github.com:wdanilo/container.git
      commit: cd137cdfa6059cc267aa865d78bbbf0a17a4c657
extra-deps:
  - data-repr-1.0
  - ghcjs-dom-0.2.3.0
  - data-layer-1.0.3
  - functor-utils-1.0
  - lens-utils-1.0
  - string-qq-0.0.2
  - tuple-0.3.0.2
  - typelevel-1.0.2
  - OneTuple-0.2.1
  - data-construction-1.0
