resolver:
  name: nbo-gui-20160201
  location: https://bitbucket.org/NewByteOrder/stack-snapshots/raw/master/nbo-gui-20160201.yaml
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160201_ghc-7.10.3:
        url: "https://s3-eu-west-1.amazonaws.com/nbo-toolchain/ghcjs/ghcjs-0.2.0.20160201-dupa.tar.gz"
ghc-options:
  nodelab: -DGHCJS_BROWSER
packages:
  - .
  - location: ../libs/luna-empire-api
    extra-dep: true
  - location: ../libs/luna-empire-api-json
    extra-dep: true
  - location: ../libs/scope-searcher
    extra-dep: true
  - location:
      git: https://github.com/wdanilo/prologue.git
      # commit: 9ba882921b6e2527923bbb0f9ba54c41b43a8135  # 1.0.6
      commit: 48c846701e796d28734f96524ba1e0b36cce57c0  # 1.0.2
    extra-dep: true
  - location:
      git: https://github.com/wdanilo/container.git
      commit: cd137cdfa6059cc267aa865d78bbbf0a17a4c657
    extra-dep: true
  - location: ../../libs/hsprocessing
  # - location:
  #     git: https://github.com/wdanilo/hsprocessing.git
  #     commit: 944ac84a9625782291adad8db4c6432d2fbeccaa
  #   extra-dep: true
  - location:
      git:    https://github.com/wdanilo/data-repr.git
      commit: a725e4dad9b0916514662e917cef692a91a51029

extra-deps:
  - data-rtuple-1.0
  - language-glsl-0.2.0
  - prettyclass-1.0.0.0
  - data-repr-1.0.1
