packages:
- ../../../libs/config
- ../../../libs/luna/initializer
- ../../../libs/utils
- ../../../third-party/fgl
- ../../../tools/initializer
extra-deps:
- protocol-buffers-2.1.3
resolver: lts-2.18

