resolver: lts-4.1

packages:
    - location: ../../libs/bus
      extra-dep: true
    - location: ../../libs/bus-binary
      extra-dep: true
    - location: ../../libs/config
      extra-dep: true
    # - location: ../../libs/luna-empire
    #   extra-dep: true
    - location: ../../libs/luna-empire-api
      extra-dep: true
    - location: ../../libs/luna-empire-api-json
      extra-dep: true
    - location: ../../libs/luna/typechecker
      extra-dep: true
    - location: ../../libs/old-utils
      extra-dep: true
    - location: ../../libs/rpc
      extra-dep: true
    - location: ../../libs/utils
      extra-dep: true
    - location: ../../libs/ws-connector
      extra-dep: true
    - location: ../../libs/batch/plugins/luna-empire
      extra-dep: true
    - location: ../../tools/batch/plugins/ws-connector
    - location: ../../tools/batch/plugins/broker
    - location: ../../tools/batch/plugins/bus-logger
    # - location: ../../tools/batch/plugins/luna-empire
    - location:
          git: https://github.com/wdanilo/container.git
          commit: e9ecbe4faf286aa681de6df224d6d7aa2eff3791
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/convert.git
          commit: d0bb22989f58932c54c7c9c1e3922958c002d02e
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/data-base.git
          commit: 51a583bc68d3ed8bdb867a58ec41014863121533
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/data-construction.git
          commit: 29c97b37c8d23ee4345adaf7cb61609f1626641b
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/data-layer.git
          commit: 4472a6e17911680561021bb4c932b1052f909f77
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/data-repr.git
          commit: f8f3c0cc15b5cf7f76b94db9ddb2b4f326a4a26f
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/data-result.git
          commit: a40ff30ee8b6f36c85b2890e8356ef0583cd5f2a
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/dependent-state.git
          commit: 50ac8686bd5b5dbd5fb29aebb19d5e4d09487cfe
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/functor-utils.git
          commit: aa37a38de3bd4c0b4b105773299a766a129062fb
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/impossible.git
          commit: c5556018a7cd5cba9ecdc00c4898da0520a177d1
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/lens-utils.git
          commit: 7e22132987ab75f6d5cb24e2f12b3dd7cfacc9be
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/poly-control.git
          commit: 5df51c7846cca02082204bdfce18285d70f6cd32
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/prologue.git
          commit: 6c2e784ececf85573973439162953c01554fe49e
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/type-cache.git
          commit: eee76a96bdd1d442299cecdcd1e445d76eef3b1a
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/typelevel.git
          commit: 701a299dc0232833756c8d71123c4c2d50d584d9
      extra-dep: true
    - location:
          git: https://github.com/wdanilo/data-construction.git
          commit: 29c97b37c8d23ee4345adaf7cb61609f1626641b
      extra-dep: true

extra-deps:
    - ghc-session-0.1.2.0
    - graphviz-2999.18.0.2
    - string-qq-0.0.2
    - error-util-0.0.1.1
    - cond-0.4.1.1
    - tuple-0.3.0.2
    - OneTuple-0.2.1
    - docopt-0.7.0.4
    - saltine-0.0.0.4

ghc-options:
    "*": -DFastCompilation -threaded -O

local-bin-path: ../../dist/bin
